services:
  web:
    build: .
    secrets:
      - euskalmet_private_apikey
      - euskalmet_fingerprint
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1.5G
    memswap_limit: 40G
secrets:
  euskalmet_private_apikey:
    file: ../EuskalmetAPI/privateKey.pem
  euskalmet_fingerprint:
    file: ../EuskalmetAPI/fingerPrint.txt