services:
  app:
    build: .
    secrets:
      - euskalmet_private_apikey
      - euskalmet_fingerprint
    expose:
      - "8000"
    networks:
      - docker-network 
    command: gunicorn --bind 0.0.0.0:8000 wsgi:app --timeout 180
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - docker-network

secrets:
  euskalmet_private_apikey:
    file: ./EuskalmetAPI/privateKey.pem
  euskalmet_fingerprint:
    file: ./EuskalmetAPI/fingerPrint.txt

networks:
  docker-network:

