services:
  web:
    build: .
    secrets:
      - euskalmet_private_apikey
      - euskalmet_fingerprint
    ports:
      - "80:5000"
secrets:
  euskalmet_private_apikey:
    file: ../EuskalmetAPI/privateKey.pem
  euskalmet_fingerprint:
    file: ../EuskalmetAPI/fingerPrint.txt