services:
  web:
    build: .
    secrets:
      - euskalmet_private_apikey
      - euskalmet_fingerprint
      - tls_cert
      - tls_key
    ports:
      - "443:5000"
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1.5G
    memswap_limit: 40G
secrets:
  euskalmet_private_apikey:
    file: ../EuskalmetAPI/privateKey.pem
  euskalmet_fingerprint:
    file: ../EuskalmetAPI/fingerPrint.txt
  tls_cert:
    file: ../odemapa_tls/cert.pem
  tls_key:
    file: ../odemapa_tls/privkey.pem